name: Ubuntu Server Compile X86
on:
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Ubuntu Server
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo docker image prune --all --force
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo apt-get -y update
          sudo apt-get -y install aria2 wget curl ffmpeg nodejs npm golang-go
          sudo systemctl daemon-reload
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          # sudo timedatectl set-timezone Asia/Jakarta
          sudo hostnamectl set-hostname chewy

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup for AI Code
        run: |
          curl -fsSL https://opencode.ai/install | bash
          curl -fsSL https://claude.ai/install.sh | bash

      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          limit-access-to-actor: true
          wait-timeout-minutes: 5
            
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: compiled
          include-hidden-files: true
          path: |
            ~/.claude
            ~/.reasonix
            ~/.local/*/opencode
            ${{ github.workspace }}/*
